### PR TITLE
save a whopping 12 bytes from Color struct

### PR DESCRIPTION
**Pull request by Rylxnd**
how generous of us ;)

### CODE REVIEW

**Comment by ReiDaTecnologia** [comment]
image

**Comment by ReiDaTecnologia** [comment]
well yes but actually no
1mb i would understand but 12 bytes? '_'

**Comment by ShufflePerson** [comment]
> well yes but actually no 1mb i would understand but 12 bytes? '_'

12 bytes is 12 bytes, imagine everything you can do with it.  
You could for example store the number 4096!! 


Jokes aside, even saving 12 bytes is worth it, any and all optimizations, as long as they don'truin the codebase, should be made if someone has the time.

**Comment by ReiDaTecnologia** [comment]
> > well yes but actually no 1mb i would understand but 12 bytes? '_'
> 
> 12 bytes is 12 bytes, imagine everything you can do with it. You could for example store the number 7.9228163e+28!!
> 
> Jokes aside, even saving 12 bytes is worth it, any and all optimizations, as long as they don'truin the codebase, should be made if someone has the time.

Honestly i wish the modern gaming industry cared that much but they only care with money and in saving em (optimization and time is a waste of money for em, sadly)

**Comment by Reguas** [comment]
> You could for example store the number 7.9228163e+28!!

10^(10^30.052154446) is quite a big number, I'm pretty sure you can't store it using just 12 bytes

**Comment by ShufflePerson** [comment]
> > You could for example store the number 7.9228163e+28!!
> 
> 10^(10^30.052154446) is quite a big number, I'm pretty sure you can't store it using just 12 bytes

12 bytes = 12*8 = 96 bits = 2^96 = 7.9228163e+28

**Comment by Reguas** [comment]
> > > You could for example store the number 7.9228163e+28!!
> > 
> > 
> > 10^(10^30.052154446) is quite a big number, I'm pretty sure you can't store it using just 12 bytes
> 
> 12 bytes = 12*8 = 96 bits = 2^96 = 7.9228163e+28

7.9228163e+28!! = 10^(10^30.052154446)

**Comment by MoneyWasted** [comment]
> > You could for example store the number 7.9228163e+28!!
> 
> 10^(10^30.052154446) is quite a big number, I'm pretty sure you can't store it using just 12 bytes

i think he is talking about all the possible combinations of 12 bytes. that number makes more sense.

**Comment by Reguas** [comment]
> > > You could for example store the number 7.9228163e+28!!
> > 
> > 
> > 10^(10^30.052154446) is quite a big number, I'm pretty sure you can't store it using just 12 bytes
> 
> i think he is talking about all the possible combinations of 12 bytes. that number makes more sense.

No I'm not, 7.9228163e+28!! ≈ 10^(10^30.052154446)

**Comment by pongo1231** [comment]
`cstdint` needs to be included in both headers. Also the types inside `std` are preferred over the ones in the global namespace (so e.g. `uint8_t` -> `std::uint8_t`).

**Comment by ReiDaTecnologia** [comment]
Come on guys, obviously it can store 12 cuz each byte is either 0 or 1 :p

**Comment by ShufflePerson** [comment]
> Come on guys, obviously it can store 12 cuz each byte is either 0 or 1 :p

me when byte != bit

**Comment by ReiDaTecnologia** [comment]
> > Come on guys, obviously it can store 12 cuz each byte is either 0 or 1 :p
> 
> me when byte != bit
Ops, i forgot that _bit_ XD

**Comment by ShufflePerson** [comment]
> > > Come on guys, obviously it can store 12 cuz each byte is either 0 or 1 :p
> > 
> > 
> > me when byte != bit
> 
> Ops, i forgot that _bit_ XD

LMFAO, I love that dad joke. Made me chuckle so hard

**Pull request merged**
