### PR TITLE
Added Effect: "Alt Strat"

### PR DESCRIPTION
**Pull request by ubscal**
Requested in https://github.com/gta-chaos-mod/ChaosModV/issues/1056#issue-857994207

### CODE REVIEW

**Comment by ProfessorBiddle** [comment]
A different name for this might be a good idea for the people who don't watch Matt's twitch/youtube. Maybe 'Player Swap' can make a return?

**Comment by ubscal** [comment]
> A different name for this might be a good idea for the people who don't watch Matt's twitch/youtube. Maybe 'Player Swap' can make a return?

Player Swap actually triggered the Player Swap Camera, This holds down the "Alt" key, which brings the menu up. I'm pretty sure its just called "Alt Strat" in GTAV Speedrunning, but I could be wrong.

**Comment by Da-Best** [comment]
isnt player swap already an effect/ was an effect where it put you in the clouds 

I don't want people to be confused on alt strat and player swap

**Comment by ubscal** [comment]
> isnt player swap already an effect/ was an effect where it put you in the clouds
> 
> I don't want people to be confused on alt strat and player swap

Player swap seems to have been removed in the new patch, this effect just holds down the left alt key. I'm working on redoing this effect to not just depend on the player swap key being on left alt.

**Comment by ProfessorBiddle** [comment]
>  I'm working on redoing this effect to not just depend on the player swap key being on left alt.

the way it is now should be fine, 'INPUT_CHARACTER_WHEEL' should be the same regardless of control settings

https://github.com/MAFINS/MenyooSP/blob/master/Solution/source/Scripting/enums.h

**Comment by ubscal** [comment]
> > I'm working on redoing this effect to not just depend on the player swap key being on left alt.
> 
> the way it is now should be fine, 'INPUT_CHARACTER_WHEEL' should be the same regardless of control settings
> 
> https://github.com/MAFINS/MenyooSP/blob/master/Solution/source/Scripting/enums.h

Ah thank you, I must've confused myself into thinking that my code only held down the left alt key.

**Comment by Last0xygen** [comment]
"Quick Update" 😅 
Just tried the effect, could be avoided by bringing up the phone. 
But in general, while it was a funny idea its just not too different from "0.2x Gamespeed", so i don't think this would be a good addition to the mod. sorry

**Comment by ubscal** [comment]
> "Quick Update" 😅 Just tried the effect, could be avoided by bringing up the phone. But in general, while it was a funny idea its just not too different from "0.2x Gamespeed", so i don't think this would be a good addition to the mod. sorry

imma be real with you i completely forgot I made this LMAO, and yea i totally agree with you.

**Pull request closed without merging**
