### PR TITLE
News Team ticker improvements

### PR DESCRIPTION
**Pull request by juhana**
Changed the ticker style in News Team to match what's shown in story mode (all-caps) and changed the text to be more "headlinese" and remove repetition

### CODE REVIEW

**Comment by Last0xygen** [comment]
🙄😅

**Comment by TheRealAyCe** [comment]
If Twitch voting is active, maybe also TWITCH CHAT: NO CHANCE?

**Comment by juhana** [comment]
Good idea, I've added that to the PR.

**Comment by pongo1231** [comment]
The headline change won't be applicable anymore since 6a90df9 - at least in its current state.

**Comment by TheRealAyCe** [comment]
Random headlines? Even better :D

**Comment by Last0xygen** [comment]
i don't think this is needed anymore since https://github.com/gta-chaos-mod/ChaosModV/commit/6a90df9d03cf0321c2197803ba4cf4b0ce01781b

**Pull request closed without merging**
