### PR TITLE
Added Effect 'You're A Wizard, Franklin'

### PR DESCRIPTION
**Pull request by Last0xygen**
Spawns an invisible MK2 with an attached broomstick taht the player can drive
Fix https://github.com/gta-chaos-mod/ChaosModV/issues/1158

### CODE REVIEW

**Comment by Mo-xii** [comment]
I'm curious to know why you set the broom as not longer needed : "SET_OBJECT_AS_NO_LONGER_NEEDED(&broom)"

Because very quickly we just have a completely invisble Opressor laying around. And if you want to despawn it, shouldn't you despawn the Opressor aswell?

**Comment by Last0xygen** [comment]
I tested it and it didn’t despawn for everything I tried 🤷‍♂️  did you manage to make it just despawn the broom? 🤔

**Comment by Mo-xii** [comment]
Yeah tested this afternoon. If I walk 10m away and look away it despawns the broom everytime. After that I can just drive the invisible Opressor. 

That behavior is consistent with objects marked as no longer needed, like the ramp of the Ramp Jam effect.

**Comment by Last0xygen** [comment]
Well f me then I guess. I’ll adjust it, thx for testing

**Pull request merged**
