### PR TITLE
Added "Spawn Griefer Squad" effect

### PR DESCRIPTION
**Pull request by OnlyRealNubs**
Spawns Jesus, Alien, Impotent Rage and Juggernaut.

### CODE REVIEW

**Comment by Reguas** [comment]
= instant death + multiple fails in a row in mission?

**Comment by OnlyRealNubs** [comment]
I mean yea. That's why have fail safe incase that does happen. But griefer jesus usually instantly kills one of them when they spawn in.

**Comment by OnlyRealNubs** [comment]
Honestly just running out of ideas lol

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/2106
Would just result in a death loop, getting instakilled. Also each effect has its own value, combining them makes the single spawn „obsolete“

**Pull request closed without merging**
