### PR TITLE
Added new Effect Cola Rain

### PR DESCRIPTION
**Pull request by igerlster**
Effect is Cola rain and random no health. Cola restores health.

It refers to GTAV speedrunner DarkViperAU (he likes Cola and No-Damage Runs)

Its a very simple effect with code from MoneyRain and ohco.

Hope to add more stuff later on. Was not sure if i can call it DarkViperAU  effect so i called it AustralienGuy.

### CODE REVIEW

**Comment by TheRealAyCe** [comment]
First it's "Australian". Second, what's wrong with "Cola Rain"?

**Comment by igerlster** [comment]
Oh nooo, i googled how to write Australian and still spelled it wrong...  i thought i call it something related to DarkViper... maybe "Matt's Rain" is ok, since it's not about Cola

**Comment by igerlster** [comment]
Ok Changed internal name to Cola Rain and Effect Name to "Matt's Rain"

**Comment by TheRealAyCe** [comment]
The reference may be too niche. I too like watching Matt play Chaos but for example "Merryweather Fleet's here Bro" was renamed to "Mercenaries" to make it less specific to him, since there are plenty of other people playing Chaos.

**Comment by igerlster** [comment]
Maybe "Pepsi Man" ? Since it's raining Coke it could refer to anyone ?

**Comment by igerlster** [comment]
Oh.. i broke my pull request, will make a new one...

**Pull request closed without merging**
