### PR TITLE
Added "Spawn Casino Game" effect

### PR DESCRIPTION
**Pull request by OnlyRealNubs**
This effect spawns a slot machine in few feet in front of the player.

### CODE REVIEW

**Comment by OnlyRealNubs** [comment]
Inspiration from #2801

**Comment by Last0xygen** [comment]
If it’s not usable indon. think this would be a good effect

**Comment by OnlyRealNubs** [comment]
> If it’s not usable i don’t think this would be a good effect

Can you please describe what you mean?

**Comment by Last0xygen** [comment]
> > If it’s not usable i don’t think this would be a good effect
> 
> Can you please describe what you mean?

Can you play the slot machine? If not, it’s like the „quick sprunk stop“ effect 😅

**Comment by OnlyRealNubs** [comment]
> > > If it’s not usable i don’t think this would be a good effect
> > 
> > 
> > Can you please describe what you mean?
> 
> Can you play the slot machine? If not, it’s like the „quick sprunk stop“ effect 😅

No you can’t. It just spawns it. I don’t think I could make it actually playable. But could randomly add or deduct the players money as if they did play it if you like.

**Pull request closed without merging**
