### PR TITLE
Added Effect 'Spawn Angry Jimmy'

### PR DESCRIPTION
**Pull request by MoneyWasted**
Jimmy can finally get revenge on you for all the times you’ve been mean to him.

### CODE REVIEW

**Comment by pongo1231** [comment]
Fixed some issues that prevented me from compiling it successfully and renamed "Angry Jimmy" to "Jealous Jimmy".

**Comment by DEATHCON1** [comment]
Could Jimmy be wearing his tactical outfit for this effect? It'd be more fitting with the gun he's given...

**Comment by MoneyWasted** [comment]
> Could Jimmy be wearing his tactical outfit for this effect? It'd be more fitting with the gun he's given...

A lot of the stuff that Jimmy wears during that mission is just "attached" on him. It's not clothing, such as the helmet, goggles, and armor is an object attached to the ped.

**Comment by DEATHCON1** [comment]
> > Could Jimmy be wearing his tactical outfit for this effect? It'd be more fitting with the gun he's given...
> 
> A lot of the stuff that Jimmy wears during that mission is just "attached" on him. It's not clothing, such as the helmet, goggles, and armor is an object attached to the ped.

Okay, well, could he wear the tactical clothing and objects from that mission?

**Pull request merged**
