### PR TITLE
Fake Crash improvements

### PR DESCRIPTION
**Pull request by ProfessorBiddle**
Add chance for screen to go black, and add variation to the pause and skip.

### CODE REVIEW

**Comment by DestroyerXyz** [comment]
How about also sort of lagging sometimes during fake crash?

**Comment by ProfessorBiddle** [comment]
> How about also sort of lagging sometimes during fake crash?

What do you mean?

**Comment by Last0xygen** [comment]
There is already a lag effect before „crashing“

**Comment by lZevex** [comment]
Is it possible to reduce the frequency of the effect?

**Comment by ProfessorBiddle** [comment]
> Is it possible to reduce the frequency of the effect?

you can change the effect weights in the config app

**Comment by lZevex** [comment]
The effect is starting to happen too often for people to fall for it, maybe you could make the frequency of the effect unadjustable?

**Comment by Last0xygen** [comment]
imho drawing a black screen wont be a good addition. it wont convince someone "more", as this usually is not a reaction of the game on crashing

**Pull request closed without merging**
