### PR TITLE
Added "Teleport to Waypoint" to fake tp list

### PR DESCRIPTION
**Pull request by OnlyRealNubs**
This is just a functional version of my previous attempt here: #2785

### CODE REVIEW

**Comment by OnlyRealNubs** [comment]
> _opens code review_ Every single line has changes _closes code review_

Something must be wrong with github. I only made changes to the list of fake tp locations and the code inside the fake tp start function.

**Comment by Goorakh** [comment]
> > _opens code review_ Every single line has changes _closes code review_
> 
> Something must be wrong with github. I only made changes to the list of fake tp locations and the code inside the fake tp start function.

Most likely it's your IDE auto-changing the line endings

**Comment by Goorakh** [comment]
Also, did you miss #2367 ? 😅

**Comment by OnlyRealNubs** [comment]
> Also, did you miss #2367 ? 😅

oof. I spent so *much* time writing those 4 lines of code.

**Pull request closed without merging**
