### PR TITLE
Add webpack-dev-server

### PR DESCRIPTION
**Pull request by byhemechi**

### CODE REVIEW

**Comment by pongo1231** [comment]
Tagging @Elias-Graf

**Comment by Elias-Graf** [comment]
Hey, cool that you took the time to add the `webpack-dev-server`. Would you mind updating the readme? So, remove the comment about it and state how to use it? Also, is there any particular reason you resolve the `.js` file extension?

**Comment by byhemechi** [comment]
Alright, I've updated the README.

`js` files need to be resolved as `webpack-dev-server` tries to inject js files into the bundle for the hot reload and these obviously need to be resolved.

**Comment by Elias-Graf** [comment]
Okay so maybe I'm mistaken, so please, educate me. 

I thought that resolve referees to the source files that should be compiled into js, not the files which should be served.

**Comment by byhemechi** [comment]
Sorry for delay, it's required because webpack-dev-server injects itself into your scripts with a wepack require statement.

You get the same module resolution errors that importing any other js files does.

It's a really confusing error that i've been asked about many times (I'm a sysadmin)

**Comment by Elias-Graf** [comment]
Okay if you say so... I just don't want anyone thinking they should add plain javascript files. Should be good to merge @pongo1231

**Pull request merged**
