### PR TITLE
Emperor's new groove

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by OnlyRealNubs** [comment]
Might want to close this and fix up your branch. Hundreds of commits and changed files.

**Comment by OnlyRealNubs** [comment]
Also, is this meant to be a suggestion?

**Comment by marcuscollinsca** [comment]
Yeah, I remembering hearing we have to request it here on GitHub, but I didn’t exactly know what to do, did I mess something up like the coding by doing this?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OnlyRealNubs** [comment]
No you didn't break anything as it's a pull-request and hasn't been merged. But I'm still confused on what you're doing. Are you suggesting anew effect for ChaosMod or are you adding an effect? (Adding more code)

**Pull request closed without merging**
