### PR TITLE
Added Effect  "Meele Only"

### PR DESCRIPTION
**Pull request by ubscal**
Based off of https://github.com/gta-chaos-mod/ChaosModV/issues/1209

Forces every Ped and the player to use their fists, they cannot select any weapons until the effect is over.

### CODE REVIEW

**Comment by LordRygar** [comment]
Nice. It's Brawling Time!  Fists will be perfectly adequate. Might be OP to allow melee weapons.

**Comment by Last0xygen** [comment]
The only difference from "Remove Weapons From Everyone"  is that you keep your weapons 🤔  i dont know if its that different :/

**Comment by ubscal** [comment]
> The only difference from "Remove Weapons From Everyone" is that you keep your weapons 🤔 i dont know if its that different :/

True,

**Comment by ubscal** [comment]
Sorry for accidently closing, fat fingered the button 🙃

**Comment by Last0xygen** [comment]
Sooooo what to do next? As I don’t see a need for another effect which removes all weapons forever/a period of time, do we still need this effect? :)

**Comment by ubscal** [comment]
> Sooooo what to do next? As I don’t see a need for another effect which removes all weapons forever/a period of time, do we still need this effect? :)

I think closing this would be a good option, Remove all weapons is too similar anyway.

**Pull request closed without merging**
