### PR TITLE
Adjust 'Replace Vehicle'

### PR DESCRIPTION
**Pull request by Last0xygen**
Spawns new Random vehicle if on foot

### CODE REVIEW

**Comment by Last0xygen** [comment]
I just realised that MP-Vehicles will respawn after 1-2 seconds. this seems to be a "known issue"
@pongo1231 do you know anything about this?

**Comment by Last0xygen** [comment]
Ah yes, did mean despawn of course. Yeah, found that too, thought there may be another way 🤔 alright, will look into that :)

**Comment by pongo1231** [comment]
Try setting `SET_ENTITY_AS_MISSION_ENTITY` on the vehicle. Setting it as a mission entity explicitly should fix the despawning. What could also help is setting the `netMissionEntity` flag in `CREATE_VEHICLE` to true.

**Comment by pongo1231** [comment]
I made some changes which could help with the despawning, however it still happens with some vehicles. Since it's the game scripts controlling that it'll probably need changes there (might be as easy as simply setting a Global). I'll merge this since it's good enough for now.

**Pull request merged**
