### PR TITLE
Hey, could you update the fork?

### PR DESCRIPTION
**Pull request by lovage31**
Hello, Could you update the fork to the original mod's final release? I would really appreciate it if you could.

### CODE REVIEW

**Comment by lovage31** [comment]
Sorry, I thought I was typing to the WebChaosMod page but accidentally I wrote here. And I'm not a coder so I don't really know how to use GitHub, so if this is out of place (other than me typing this into wrong page) sorry again.

**Comment by lovage31** [comment]
Actually I'm still not sure the if I wrote this to the right place... lol.

**Comment by Last0xygen** [comment]
You did not ;)

**Comment by lovage31** [comment]
Oh, okay then, should a reopen this? @Last0xygen

**Comment by Last0xygen** [comment]
What? No… this is the wrong place ;)

**Comment by lovage31** [comment]
> What? No… this is the wrong place ;)

Oookay... So what should I do then, as you can see as bright as daylight; I am confused haha.

**Comment by Last0xygen** [comment]
Try contacting https://github.com/CaveFire, the maintainer of the fork 🤷‍♂️

**Comment by lovage31** [comment]
I thought of that but his twitter seemed a bit inactive so i figured trying to contact him from here seemed more logical to me for some reason. Anyways thanks for your help, have a nice day.

**Pull request closed without merging**
