### PR TITLE
Implement Realistic Hacking

### PR DESCRIPTION
**Pull request by drunderscore**
Using the Hacking_PC scaleform, we emulate what would happen during The
Bureau Raid (roof entry), and insert our own custom words, win phrases,
and fail result.

A lot of moving parts to this, so I encourage a thorough review, making
sure no part can break accidentally :^)

### CODE REVIEW

**Comment by drunderscore** [comment]
Here's a bit of what it's like: https://streamable.com/e8dqaf

**Review by Last0xygen — CHANGES_REQUESTED** [review]
* unnecessary EffectsInfo-Changes

**Comment by Last0xygen** [comment]
Nice work!
Although i thoguht it should kill you if you didn't solve it in time, this would cause problems once this effect would be set as a short effect or with a really short time.
One thing i'm confused about: your streamable-link doesnt show any time-bar for the effect, which should be visible or am i missing something?

**Comment by drunderscore** [comment]
> ...Although i thoguht it should kill you if you didn't solve it in time, this would cause problems once this effect would be set as a short effect or with a really short time.

Definitely a good idea, I'll just kill on timeout as well.

> ...One thing i'm confused about: your streamable-link doesnt show any time-bar for the effect, which should be visible or am i missing something?

It is visible, it's simply that when I loaded the mod, I paused the timer (ctrl + -), and then selected the effect from the debug menu, which reset the timer. Because the timer is paused, there isn't any progress to see :^)

**Comment by pongo1231** [comment]
Good job with this one, really liking it :)

**Pull request merged**
