### PR TITLE
Fix Phone being stuck on screen during "Realistic Hacking" minigame.

### PR DESCRIPTION
**Pull request by MoneyWasted**
As seen in DarkViperAU's steam he got stuck with the phone on his screen being unable to complete the mini game. This pull request should fix that issue by "destroying" the phone when the effect is started.

### CODE REVIEW

**Comment by MoneyWasted** [comment]
Ignore the merge pull requests I was updating my fork.

**Review by kolyaventuri — APPROVED** [review]

**Comment by Last0xygen** [comment]
Doesn’t this change have softlock-potential, if The phone gets destroyed on an important call?

**Comment by kolyaventuri** [comment]
> Doesn’t this change have softlock-potential, if The phone gets destroyed on an important call?

Yes, however typically during the call the phone screen isn't visible

**Comment by SeanMirrsen** [comment]
The phone menu being up causes the softlock with the hacking minigame, not the call. So while there will still be a risk of softlocking, it will be reduced overall.

**Comment by Last0xygen** [comment]
🤔 are you sure? Things requiring your decision like helping Stacy/ jizzle/ amanda or not

**Comment by SeanMirrsen** [comment]
Well I'm obviously not *sure*, but it seems like it'd be a better option.

Maybe the phone can be force-closed instead of being destroyed, delaying the effect activation until the phone UI is no longer active?

**Comment by Last0xygen** [comment]
Yeah, i‘d personally prefer the effect to be waiting for the phone to be removed by itself rather than forcing it :)

**Comment by TheRealAyCe** [comment]
Just connecting this pull request with the bugreport: https://github.com/gta-chaos-mod/ChaosModV/issues/382

**Pull request closed without merging**
