### PR TITLE
Added Effect Merryweather Here

### PR DESCRIPTION
**Pull request by Last0xygen**
Spawns a buzzard with 4 merryweather guys in it, equiped with SMGs (i thought rocket launchers would be too overkill)
Requested in https://github.com/gta-chaos-mod/ChaosModV/issues/61

### CODE REVIEW

**Comment by pongo1231** [comment]
Should persistently spawn mercenaries in both Buzzards and in Mesas from a distance away (check if they either died or are too far away, mark them as despawnable and spawn new ones if so), also would prefer a more generic effect name like "Mercenaries".

**Comment by pongo1231** [comment]
In this case you should use the normal `CREATE_` natives instead of the custom pool entity functions. Those exist for entities which should persist longer than `SET_ENTITY_AS_NO_LONGER_NEEDED` allows them to but don't have their own management logic (which this effect does). I know it's not documented anywhere and I definitely should look into noting that down somewhere for everyone to see, I'm just saying that here now.

Also a distance check would definitely be a great addition to ensure there are always mercenaries close by if the player manages to escape them (a few hundred meters or so).

**Comment by Last0xygen** [comment]
Changed it to use the native CREATE_ methods.
A distance-Check to 300 units has already been implemented

**Comment by pongo1231** [comment]
Didn't see the existing distance check, my bad.

There has been a weird issue with neither enemies nor vehicles spawned by this not despawning at all (even after the effect stops), I've fixed this by setting them as mission entities just before marking them for despawning. I've replaced the existing `SET_X_AS_NO_LONGER_NEEDED` natives with custom functions which do this so this "fix" is applied to every effect.

**Pull request merged**
