### PR TITLE
Added Effect 'Walk On Water'

### PR DESCRIPTION
**Pull request by Last0xygen**
Enables walking and driving on water (player only)
(Possible) Fix https://github.com/gta-chaos-mod/ChaosModV/issues/144

### CODE REVIEW

**Comment by pongo1231** [comment]
Doesn't seem to work for me, even if I try to teleport above the ocean my player just falls into the water as usual.

**Comment by Last0xygen** [comment]
Hey, maybe i should wait for the model to load before using it 😂

**Comment by pongo1231** [comment]
Works now, though I noticed if the player is already swimming in water when this effect triggers it'll simply push them under water and spawn the object above them. Checking if the player is already in water and teleporting them above it will fix that.

**Comment by Last0xygen** [comment]
Good finding, fixed it

**Comment by pongo1231** [comment]
Perfect

**Pull request merged**
