### PR TITLE
New Effect "Where's The Funeral?"

### PR DESCRIPTION
**Pull request by EliRickard**
Spawns Romero Hurse @ Player Coords

### CODE REVIEW

**Review by kolyaventuri — CHANGES_REQUESTED** [review]
Is there a tabs vs spaces change here? EffectsInfoh.h, VehsSpawner.cpp, and Effects.cs seemingly have every single line "changed."

The effect added looks fine, but can you clean up the diff?

**Comment by EliRickard** [comment]
Fixed!

**Review by kolyaventuri — APPROVED** [review]
Sweet! Thanks, looks good

**Comment by EliRickard** [comment]
Intended for separated New "Nap Time" Effect PR ^

**Pull request closed without merging**
